site:
  name: FMS IT Solution PLC
  site: 'https://fmsitsolution.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: FMS IT Solution PLC — Crafting Games People Love to Play
    template: '%s — FMS IT Solution PLC'
  description: 'From concept to launch, FMS IT Solution PLC creates engaging, high-retention games across mobile, PC, and web that captivate players.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: FMS IT Solution PLC
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
